import 'dart:ui';
import '../../data/datasources/local_database.dart';

class AchievementStrings {
  AchievementStrings._();

  static String get _storedLocale => LocalDatabase.instance.getLocale();
  static String get _locale {
    if (_storedLocale == 'system') {
      try {
        final sysCode = PlatformDispatcher.instance.locale.languageCode;
        if (['en', 'es', 'pt', 'de', 'fr', 'ja', 'ko', 'id', 'zh', 'hi', 'ar'].contains(sysCode)) {
          return sysCode;
        }
      } catch (_) {}
      return 'en';
    }
    return _storedLocale;
  }

  static String get(String key) {
    return _strings[key]?[_locale] ?? _strings[key]?['en'] ?? key;
  }

  static final Map<String, Map<String, String>> _strings = {
    'ach_title_first_solve': {'en': 'First Steps', 'id': 'Langkah Pertama', 'es': 'Primeros Pasos', 'pt': 'Primeiros Passos', 'de': 'Erste Schritte', 'fr': 'Premiers Pas', 'ja': '最初の一歩', 'ko': '첫 걸음', 'zh': '第一步', 'hi': 'पहला कदम', 'ar': 'الخطوات الأولى'},
    'ach_desc_first_solve': {'en': 'Solve your first puzzle', 'id': 'Selesaikan teka-teki pertamamu', 'es': 'Resuelve tu primer rompecabezas', 'pt': 'Resolva seu primeiro quebra-cabeça', 'de': 'Löse dein erstes Rätsel', 'fr': 'Résolvez votre premier puzzle', 'ja': '最初のパズルを解く', 'ko': '첫 퍼즐 해결하기', 'zh': '解决您的第一个难题', 'hi': 'अपनी पहली पहेली हल करें', 'ar': 'حل لغزك الأول'},
    'ach_title_no_hint_solve': {'en': 'Pure Mind', 'id': 'Pikiran Murni', 'es': 'Mente Pura', 'pt': 'Mente Pura', 'de': 'Reiner Geist', 'fr': 'Esprit Pur', 'ja': 'ピュアマインド', 'ko': '순수한 마음', 'zh': '纯净心灵', 'hi': 'शुद्ध मन', 'ar': 'عقل صافٍ'},
    'ach_desc_no_hint_solve': {'en': 'Solve a puzzle without any hints', 'id': 'Selesaikan teka-teki tanpa petunjuk', 'es': 'Resuelve un rompecabezas sin pistas', 'pt': 'Resolva um quebra-cabeça sem dicas', 'de': 'Löse ein Rätsel ohne Tipps', 'fr': 'Résolvez un puzzle sans indices', 'ja': 'ヒントなしでパズルを解く', 'ko': '힌트 없이 퍼즐 해결하기', 'zh': '在没有任何提示的情况下解决难题', 'hi': 'बिना किसी संकेत के एक पहेली हल करें', 'ar': 'حل لغزًا بدون أي تلميحات'},
    'ach_title_speed_demon_30': {'en': 'Speed Demon', 'id': 'Setan Kecepatan', 'es': 'Demonio de la Velocidad', 'pt': 'Demônio da Velocidade', 'de': 'Geschwindigkeitsteufel', 'fr': 'Démon de la Vitesse', 'ja': 'スピード狂', 'ko': '스피드광', 'zh': '速度狂魔', 'hi': 'स्पीड डेमन', 'ar': 'شيطان السرعة'},
    'ach_desc_speed_demon_30': {'en': 'Solve a puzzle in under 30 seconds', 'id': 'Selesaikan teka-teki di bawah 30 detik', 'es': 'Resuelve un rompecabezas en menos de 30 segundos', 'pt': 'Resolva um quebra-cabeça em menos de 30 segundos', 'de': 'Löse ein Rätsel in unter 30 Sekunden', 'fr': 'Résolvez un puzzle en moins de 30 secondes', 'ja': '30秒以内にパズルを解く', 'ko': '30초 이내에 퍼즐 해결하기', 'zh': '在30秒内解决一个难题', 'hi': '30 सेकंड से कम समय में पहेली हल करें', 'ar': 'حل لغزًا في أقل من 30 ثانية'},
    'ach_title_three_stars': {'en': 'Perfect Score', 'id': 'Skor Sempurna', 'es': 'Puntuación Perfecta', 'pt': 'Pontuação Perfeita', 'de': 'Perfektes Ergebnis', 'fr': 'Score Parfait', 'ja': 'パーフェクトスコア', 'ko': '완벽한 점수', 'zh': '满分', 'hi': 'परफेक्ट स्कोर', 'ar': 'درجة كاملة'},
    'ach_desc_three_stars': {'en': 'Get 3 stars on any puzzle', 'id': 'Dapatkan 3 bintang di teka-teki apa pun', 'es': 'Obtén 3 estrellas en cualquier rompecabezas', 'pt': 'Ganhe 3 estrelas em qualquer quebra-cabeça', 'de': 'Erhalte 3 Sterne in einem beliebigen Rätsel', 'fr': 'Obtenez 3 étoiles sur n\'importe quel puzzle', 'ja': '任意のパズルで星3を獲得', 'ko': '아무 퍼즐에서나 별 3개 얻기', 'zh': '在任何难题上获得3颗星', 'hi': 'किसी भी पहेली पर 3 स्टार प्राप्त करें', 'ar': 'احصل على 3 نجوم في أي لغز'},
    'ach_title_campaign_10': {'en': 'Getting Started', 'id': 'Mulai Memanas', 'es': 'Empezando', 'pt': 'Começando', 'de': 'Aller Anfang', 'fr': 'Pour Commencer', 'ja': 'はじまり', 'ko': '시작하기', 'zh': '初露锋芒', 'hi': 'शुरुआत', 'ar': 'البداية'},
    'ach_desc_campaign_10': {'en': 'Complete 10 campaign levels', 'id': 'Selesaikan 10 level kampanye', 'es': 'Completa 10 niveles de campaña', 'pt': 'Complete 10 níveis de campanha', 'de': 'Schließe 10 Kampagnen-Level ab', 'fr': 'Terminez 10 niveaux de campagne', 'ja': 'キャンペーンを10レベルクリア', 'ko': '캠페인 10개 레벨 완료하기', 'zh': '完成10个战役关卡', 'hi': '10 अभियान स्तर पूरे करें', 'ar': 'أكمل 10 مستويات حملة'},
    'ach_title_campaign_25': {'en': 'Quarter Way', 'id': 'Seperempat Jalan', 'es': 'Un Cuarto del Camino', 'pt': 'Um Quarto do Caminho', 'de': 'Viertel Weg', 'fr': 'Un Quart du Chemin', 'ja': '4分の1の道のり', 'ko': '4분의 1 지점', 'zh': '四分之一的路程', 'hi': 'चौथाई रास्ता', 'ar': 'ربع الطريق'},
    'ach_desc_campaign_25': {'en': 'Complete 25 campaign levels', 'id': 'Selesaikan 25 level kampanye', 'es': 'Completa 25 niveles de campaña', 'pt': 'Complete 25 níveis de campanha', 'de': 'Schließe 25 Kampagnen-Level ab', 'fr': 'Terminez 25 niveaux de campagne', 'ja': 'キャンペーンを25レベルクリア', 'ko': '캠페인 25개 레벨 완료하기', 'zh': '完成25个战役关卡', 'hi': '25 अभियान स्तर पूरे करें', 'ar': 'أكمل 25 مستوى حملة'},
    'ach_title_campaign_50': {'en': 'Halfway Hero', 'id': 'Pahlawan Setengah Jalan', 'es': 'Héroe a Medias', 'pt': 'Herói do Meio', 'de': 'Halbzeit-Held', 'fr': 'Héros à Moitié', 'ja': '半分のヒーロー', 'ko': '절반의 영웅', 'zh': '半路英雄', 'hi': 'आधा हीरो', 'ar': 'بطل منتصف الطريق'},
    'ach_desc_campaign_50': {'en': 'Complete 50 campaign levels', 'id': 'Selesaikan 50 level kampanye', 'es': 'Completa 50 niveles de campaña', 'pt': 'Complete 50 níveis de campanha', 'de': 'Schließe 50 Kampagnen-Level ab', 'fr': 'Terminez 50 niveaux de campagne', 'ja': 'キャンペーンを50レベルクリア', 'ko': '캠페인 50개 레벨 완료하기', 'zh': '完成50个战役关卡', 'hi': '50 अभियान स्तर पूरे करें', 'ar': 'أكمل 50 مستوى حملة'},
    'ach_title_campaign_100': {'en': 'Campaign Master', 'id': 'Master Kampanye', 'es': 'Maestro de Campaña', 'pt': 'Mestre da Campanha', 'de': 'Kampagnen-Meister', 'fr': 'Maître de Campagne', 'ja': 'キャンペーンマスター', 'ko': '캠페인 마스터', 'zh': '战役大师', 'hi': 'अभियान मास्टर', 'ar': 'سيد الحملة'},
    'ach_desc_campaign_100': {'en': 'Complete all 100 campaign levels', 'id': 'Selesaikan 100 level kampanye', 'es': 'Completa los 100 niveles de campaña', 'pt': 'Complete todos os 100 níveis de campanha', 'de': 'Schließe alle 100 Kampagnen-Level ab', 'fr': 'Terminez les 100 niveaux de campagne', 'ja': '100レベル全てクリア', 'ko': '캠페인 100개 레벨 모두 완료하기', 'zh': '完成所有100个战役关卡', 'hi': 'सभी 100 अभियान स्तर पूरे करें', 'ar': 'أكمل كل 100 مستوى حملة'},
    'ach_title_quick_10': {'en': 'Puzzle Lover', 'id': 'Pecinta Teka-Teki', 'es': 'Amante de los Rompecabezas', 'pt': 'Amante de Quebra-Cabeças', 'de': 'Rätsel-Liebhaber', 'fr': 'Amateur de Puzzles', 'ja': 'パズル好き', 'ko': '퍼즐 애호가', 'zh': '难题爱好者', 'hi': 'पहेली प्रेमी', 'ar': 'عاشق الألغاز'},
    'ach_desc_quick_10': {'en': 'Solve 10 quick play puzzles', 'id': 'Selesaikan 10 teka-teki main cepat', 'es': 'Resuelve 10 rompecabezas de juego rápido', 'pt': 'Resolva 10 quebra-cabeças de jogo rápido', 'de': 'Löse 10 Rätsel im schnellen Spiel', 'fr': 'Résolvez 10 puzzles de jeu rapide', 'ja': 'クイックプレイで10回パズルを解く', 'ko': '빠른 플레이 퍼즐 10개 해결하기', 'zh': '解决10个快速游玩难题', 'hi': '10 त्वरित खेल पहेलियाँ हल करें', 'ar': 'حل 10 ألغاز لعب سريع'},
    'ach_title_quick_50': {'en': 'Puzzle Addict', 'id': 'Pecandu Teka-Teki', 'es': 'Adicto a los Rompecabezas', 'pt': 'Viciado em Quebra-Cabeças', 'de': 'Rätsel-Süchtiger', 'fr': 'Accro aux Puzzles', 'ja': 'パズル中毒', 'ko': '퍼즐 중독자', 'zh': '难题狂魔', 'hi': 'पहेली व्यसनी', 'ar': 'مدمن ألغاز'},
    'ach_desc_quick_50': {'en': 'Solve 50 quick play puzzles', 'id': 'Selesaikan 50 teka-teki main cepat', 'es': 'Resuelve 50 rompecabezas de juego rápido', 'pt': 'Resolva 50 quebra-cabeças de jogo rápido', 'de': 'Löse 50 Rätsel im schnellen Spiel', 'fr': 'Résolvez 50 puzzles de jeu rapide', 'ja': 'クイックプレイで50回パズルを解く', 'ko': '빠른 플레이 퍼즐 50개 해결하기', 'zh': '解决50个快速游玩难题', 'hi': '50 त्वरित खेल पहेलियाँ हल करें', 'ar': 'حل 50 لغز لعب سريع'},
    'ach_title_all_difficulties': {'en': 'Versatile', 'id': 'Serba Bisa', 'es': 'Versátil', 'pt': 'Versátil', 'de': 'Vielseitig', 'fr': 'Polyvalent', 'ja': '多才', 'ko': '다재다능', 'zh': '全能选手', 'hi': 'बहुमुखी', 'ar': 'متعدد البراعة'},
    'ach_desc_all_difficulties': {'en': 'Solve at least one puzzle in each difficulty', 'id': 'Selesaikan setidaknya satu teka-teki di setiap kesulitan', 'es': 'Resuelve al menos un rompecabezas en cada dificultad', 'pt': 'Resolva pelo menos um quebra-cabeça em cada dificuldade', 'de': 'Löse mindestens ein Rätsel in jeder Schwierigkeit', 'fr': 'Résolvez au moins un puzzle de chaque difficulté', 'ja': '各難易度で少なくとも1回パズルを解く', 'ko': '모든 난이도에서 퍼즐 1개 이상 해결하기', 'zh': '在每个难度中至少解决一个难题', 'hi': 'प्रत्येक कठिनाई में कम से कम एक पहेली हल करें', 'ar': 'حل لغزًا واحدًا على الأقل في كل مستوى صعوبة'},
    'ach_title_hard_solver': {'en': 'Hard Mode Hero', 'id': 'Pahlawan Mode Sulit', 'es': 'Héroe del Modo Difícil', 'pt': 'Herói do Modo Difícil', 'de': 'Schwerer Modus Held', 'fr': 'Héros du Mode Difficile', 'ja': 'ハードモードの英雄', 'ko': '어려움 모드 영웅', 'zh': '困难模式英雄', 'hi': 'हार्ड मोड हीरो', 'ar': 'بطل الوضع الصعب'},
    'ach_desc_hard_solver': {'en': 'Solve 10 hard puzzles', 'id': 'Selesaikan 10 teka-teki sulit', 'es': 'Resuelve 10 rompecabezas difíciles', 'pt': 'Resolva 10 quebra-cabeças difíceis', 'de': 'Löse 10 schwere Rätsel', 'fr': 'Résolvez 10 puzzles difficiles', 'ja': 'ハードパズルを10回解く', 'ko': '어려운 퍼즐 10개 해결하기', 'zh': '解决10个困难难题', 'hi': '10 कठिन पहेलियाँ हल करें', 'ar': 'حل 10 ألغاز صعبة'},
    'ach_title_daily_first': {'en': 'Daily Player', 'id': 'Pemain Harian', 'es': 'Jugador Diario', 'pt': 'Jogador Diário', 'de': 'Täglicher Spieler', 'fr': 'Joueur Quotidien', 'ja': 'デイリープレイヤー', 'ko': '데일리 플레이어', 'zh': '日常玩家', 'hi': 'दैनिक खिलाड़ी', 'ar': 'لاعب يومي'},
    'ach_desc_daily_first': {'en': 'Complete your first daily challenge', 'id': 'Selesaikan tantangan harian pertamamu', 'es': 'Completa tu primer desafío diario', 'pt': 'Complete seu primeiro desafio diário', 'de': 'Schließe deine erste tägliche Herausforderung ab', 'fr': 'Terminez votre premier défi quotidien', 'ja': '最初のデイリーチャレンジをクリア', 'ko': '첫 데일리 챌린지 완료하기', 'zh': '完成您的第一个每日挑战', 'hi': 'अपनी पहली दैनिक चुनौती पूरी करें', 'ar': 'أكمل التحدي اليومي الأول'},
    'ach_title_streak_3': {'en': 'On a Roll', 'id': 'Sedang Panas', 'es': 'En Racha', 'pt': 'Em Alta', 'de': 'Auf einer Erfolgswelle', 'fr': 'Sur une Lancée', 'ja': '絶好調', 'ko': '연속 성공', 'zh': '势如破竹', 'hi': 'प्रवाह में', 'ar': 'في تقدم متواصل'},
    'ach_desc_streak_3': {'en': 'Maintain a 3-day streak', 'id': 'Pertahankan rentetan 3 hari', 'es': 'Mantén una racha de 3 días', 'pt': 'Mantenha uma sequência de 3 dias', 'de': 'Erreiche eine 3-Tage-Serie', 'fr': 'Maintenez une série de 3 jours', 'ja': '3日連続プレイ', 'ko': '3일 연속 기록 유지하기', 'zh': '保持3天连续记录', 'hi': '3-दिवसीय स्ट्रीक बनाए रखें', 'ar': 'حافظ على سلسلة 3 أيام'},
    'ach_title_streak_7': {'en': 'Weekly Warrior', 'id': 'Pejuang Mingguan', 'es': 'Guerrero Semanal', 'pt': 'Guerreiro Semanal', 'de': 'Wöchentlicher Krieger', 'fr': 'Guerrier Hebdomadaire', 'ja': 'ウィークリーウォリアー', 'ko': '주간 전사', 'zh': '每周战士', 'hi': 'साप्ताहिक योद्धा', 'ar': 'محارب أسبوعي'},
    'ach_desc_streak_7': {'en': 'Maintain a 7-day streak', 'id': 'Pertahankan rentetan 7 hari', 'es': 'Mantén una racha de 7 días', 'pt': 'Mantenha uma sequência de 7 dias', 'de': 'Erreiche eine 7-Tage-Serie', 'fr': 'Maintenez une série de 7 jours', 'ja': '7日連続プレイ', 'ko': '7일 연속 기록 유지하기', 'zh': '保持7天连续记录', 'hi': '7-दिवसीय स्ट्रीक बनाए रखें', 'ar': 'حافظ على سلسلة 7 أيام'},
    'ach_title_streak_30': {'en': 'Monthly Master', 'id': 'Master Bulanan', 'es': 'Maestro Mensual', 'pt': 'Mestre Mensal', 'de': 'Monatlicher Meister', 'fr': 'Maître Mensuel', 'ja': 'マンスリーマスター', 'ko': '월간 마스터', 'zh': '每月大师', 'hi': 'मासिक मास्टर', 'ar': 'سيد شهري'},
    'ach_desc_streak_30': {'en': 'Maintain a 30-day streak', 'id': 'Pertahankan rentetan 30 hari', 'es': 'Mantén una racha de 30 días', 'pt': 'Mantenha uma sequência de 30 dias', 'de': 'Erreiche eine 30-Tage-Serie', 'fr': 'Maintenez une série de 30 jours', 'ja': '30日連続プレイ', 'ko': '30일 연속 기록 유지하기', 'zh': '保持30天连续记录', 'hi': '30-दिवसीय स्ट्रीक बनाए रखें', 'ar': 'حافظ على سلسلة 30 يومًا'},
    'ach_title_speed_15': {'en': 'Lightning Fast', 'id': 'Secepat Kilat', 'es': 'A la Velocidad del Rayo', 'pt': 'Na Velocidade da Luz', 'de': 'Blitzschnell', 'fr': 'À la Vitesse de l\'Éclair', 'ja': '電光石火', 'ko': '빛의 속도', 'zh': '闪电般快速', 'hi': 'बिजली की गति', 'ar': 'سريع كالبرق'},
    'ach_desc_speed_15': {'en': 'Solve a puzzle in under 15 seconds', 'id': 'Selesaikan teka-teki di bawah 15 detik', 'es': 'Resuelve un rompecabezas en menos de 15 segundos', 'pt': 'Resolva um quebra-cabeça em menos de 15 segundos', 'de': 'Löse ein Rätsel in unter 15 Sekunden', 'fr': 'Résolvez un puzzle en moins de 15 secondes', 'ja': '15秒以内にパズルを解く', 'ko': '15초 이내에 퍼즐 해결하기', 'zh': '在15秒内解决难题', 'hi': '15 सेकंड से कम समय में पहेली हल करें', 'ar': 'حل لغزًا في أقل من 15 ثانية'},
    'ach_title_total_100': {'en': 'Centurion', 'id': 'Seratusan', 'es': 'Centurión', 'pt': 'Centurião', 'de': 'Zenturio', 'fr': 'Centurion', 'ja': 'センチュリオン', 'ko': '백인대장', 'zh': '百夫长', 'hi': 'सेंचुरियन', 'ar': 'قائد المئة'},
    'ach_desc_total_100': {'en': 'Solve 100 puzzles total', 'id': 'Selesaikan 100 teka-teki total', 'es': 'Resuelve 100 rompecabezas en total', 'pt': 'Resolva 100 quebra-cabeças no total', 'de': 'Löse insgesamt 100 Rätsel', 'fr': 'Résolvez 100 puzzles au total', 'ja': '合計100回パズルを解く', 'ko': '총 100개의 퍼즐 해결하기', 'zh': '总共解决100个难题', 'hi': 'कुल 100 पहेलियाँ हल करें', 'ar': 'حل 100 لغز إجمالاً'},
    'ach_title_stars_100': {'en': 'Star Collector', 'id': 'Kolektor Bintang', 'es': 'Coleccionista de Estrellas', 'pt': 'Colecionador de Estrelas', 'de': 'Sternesammler', 'fr': 'Collectionneur d\'Étoiles', 'ja': 'スターコレクター', 'ko': '별 수집가', 'zh': '星星收集者', 'hi': 'स्टार कलेक्टर', 'ar': 'جامع النجوم'},
    'ach_desc_stars_100': {'en': 'Earn 100 stars total', 'id': 'Dapatkan total 100 bintang', 'es': 'Gana 100 estrellas en total', 'pt': 'Ganhe 100 estrelas no total', 'de': 'Verdiene insgesamt 100 Sterne', 'fr': 'Gagnez 100 étoiles au total', 'ja': '合計100個の星を獲得', 'ko': '총 100개의 별 획득하기', 'zh': '总共获得100颗星', 'hi': 'कुल 100 स्टार अर्जित करें', 'ar': 'اكسب 100 نجمة إجمالاً'},
    'ach_title_two_step_solve': {'en': 'Efficient', 'id': 'Efisien', 'es': 'Eficiente', 'pt': 'Eficiente', 'de': 'Effizient', 'fr': 'Efficace', 'ja': '効率的', 'ko': '효율적', 'zh': '高效率', 'hi': 'कुशल', 'ar': 'فعال'},
    'ach_desc_two_step_solve': {'en': 'Solve a puzzle in only 2 steps', 'id': 'Selesaikan teka-teki hanya dalam 2 langkah', 'es': 'Resuelve un rompecabezas en solo 2 pasos', 'pt': 'Resolva um quebra-cabeça em apenas 2 passos', 'de': 'Löse ein Rätsel in nur 2 Schritten', 'fr': 'Résolvez un puzzle en seulement 2 étapes', 'ja': '2ステップのみでパズルを解く', 'ko': '단 2단계 만에 퍼즐 해결하기', 'zh': '仅用2步解决难题', 'hi': 'केवल 2 चरणों में पहेली हल करें', 'ar': 'حل لغزًا في خطوتين فقط'},
  };
}
